version: '3.7'
services:
  # Shadowsocks
  shadowsocks:
    image: shadowsocks/shadowsocks-libev
    container_name: shadowsocks
    ports:
      - 38531:8388
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=diabloly
    restart: always

  # XL2TP
  # l2tp:
  #   build:
  #     context: ./l2tp
  #   container_name: l2tp
  #   env_file:
  #     - ./l2tp/l2tp.env
  #   ports:
  #     - 4500:4500/udp
  #     - 500:500/udp
  #   restart: always
  #   privileged: true
