version: '3.7'
services:
  # Shadowsocks
  shadowsocks:
    build:
      context: ./shadowsocks
    container_name: ss-libev
    ports:
      - 38531:38531/tcp
      - 38531:38531/udp
    volumes:
      - ./shadowsocks:/etc/shadowsocks-libev
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=diabloly
    restart: always
  # HTTP PROXY
  squid:
    image: 'b4tman/squid'
    container_name: 'my-squid'
    restart: always
    ports:
      - '3128:3128'
  # XL2TP
  # l2tp:
  #   build:
  #     context: ./l2tp
  #   container_name: l2tp
  #   env_file:
  #     - ./l2tp/l2tp.env
  #   ports:
  #     - 4500:4500/udp
  #     - 500:500/udp
  #   restart: always
  #   privileged: true
