version: '3.7'
services:
  # Shadowsocks
  shadowsocks:
    image: teddysun/shadowsocks-libev
    container_name: ss
    ports:
      - 38532:38532/tcp
      - 38532:38532/udp
    volumes:
      - ./shadowsocks:/etc/shadowsocks-libev
    restart: always
  # Shadowsocks-R
  shadowsocks-r:
    image: teddysun/shadowsocks-r
    container_name: ss-r
    ports:
      - 38533:38533/tcp
      - 38533:38533/udp
    volumes:
      - ./shadowsocks-r:/etc/shadowsocks-r
    restart: always
  # XL2TPD
  xl2tp:
    image: teddysun/l2tp
    container_name: l2tp
    ports:
      - 500:500/udp
      - 4500:4500/udp
      - 1701:1701/tcp
    restart: always
    env_file:
      - ./l2tp/l2tp.env
    privileged: true
